export * from './authApi'
export * as breakdown from './breakdownApi'
export * as resource from './resourceApi'
export * as breakdownAssignUser from './breakdownAssignUserApi'
export * as assetModelSolution from './assetModelSolutionApi'
export * as assetModelSeftDiagnosia from './assetModelSeftDiagnosiaApi'
export * as serviceCategory from './serviceCategoryApi'
export * as subCategory from './subCategoryApi'
export * as serviceSubCategory from './serviceSubCategoryApi'
export * as customer from './customerApi'
export * as manufacturer from './manufacturerApi'
export * as category from './categoryApi'
export * as assetMaintenance from './assetMaintenanceApi'
export * as asset from './assetApi'
export * as assetModel from './assetModelApi'
export * as assetModelDocument from './assetModelDocumentApi'
export * as assetModelFailureType from './assetModelFailureTypeApi'
export * as AssetModelSparePart from './AssetModelSparePartApi'
export * as breakdownSpareRequest from './breakdownSpareRequestApi'
export * as user from './userApi'
export * as inventory from './iventoryApi'
export * as schedulePreventive from './schedulePreventiveApi'
export * as report from './reportApi'
export * as notification from './notificationApi'
export * as reportAssetMaintenance from './reportAssetMaintenanceApi'
export * as reportAssetDepreciation from './reportAssetDepreciationApi'
export * as building from "./buildingApi";
export * as department from "./departmentApi";
export * as floor from "./floorApi";
export * as sparePart from "./sparePartsApi";
export * as spareCategory from "./spareCategoryApi";
export * as spareSubCategory from "./spareSubCategoryApi";
export * as reportBreakdown from "./reportBreakdownApi";
export * as reportSchedulePreventive from "./reportSchedulePreventiveApi";
export * as reportAssetMaintenanceRequest from "./reportAssetMaintenanceRequestApi";
export * as auth from "./authApi";
export * as schedulePreventiveTaskRequestSparepart from "./schedulePreventiveTaskRequestSparepartApi";
export * as calibrationWork from "./calibrationWorkApi";
export * as repairContract from "./repairContractApi";
export * as amc from "./amcApi";
export * as calibrationContract from "./calibrationContract";
export * as jobSummary from "./jobSummaryApi";
export * as company from "./companyApi";
export * as propertyInspection from "./propertyInspectionApi";
export * as servicePackage from "./servicePackageApi";
export * as serviceContractor from "./serviceContractorApi";
export * as inventoryAsset from './inventoryAssetApi';